[project]
name = "spotify-app"
version = "0.1.0"
description = "An ML model to match people based on listening histories"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.104.1",
    "google-auth>=2.48.0",
    "google-cloud-storage>=3.9.0",
    "grpcio>=1.78.0",
    "httpx==0.25.2",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.22",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "starlette>=0.27.0",
    "uvicorn==0.24.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.0",
]

[tool.setuptools]
packages = [
    "training.feature_extraction",
    "training.labeling",
    "utils",
]